name: bb
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  property_change_notifier: ^0.2.0
  sqflite: ^1.3.0
  path:
  flutter_spinkit: ^4.1.2
  rxdart: ^0.23.1
  http: ^0.12.0+4
  device_info: ^0.4.2+1
  shared_preferences: ^0.5.6+3
  cached_network_image: ^2.1.0+1
  marquee: ^1.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
   - images/cat.jpg
   - images/certificate.cer
